### ISSUE TITLE
Include keras to estimator notebook on tensorflow.org ?

### ISSUE THREAD

**Issue by lamberta** [kashif/tf-keras-tutorial#1]
Hi Dr. Kashif,

Was just looking through your tf.keras notebook collection and they're great! Would you mind if we brought in the [keras to estimator notebook](https://github.com/kashif/tf-keras-tutorial/blob/master/7-estimators-multi-gpus.ipynb) to publish on tensorflow.org?

Would you mind submitting a pull request to our models repo and putting it here? https://github.com/tensorflow/models/tree/master/samples/core/tutorials/keras
(I could bring it in if you want, but just want to make sure you get credit. We also are planning to add a contributors file for our docs and will add you there, as well.)

I know your notebooks are MIT licensed (and we can add that), but just wanted to make sure it sounded ok to you.

Thanks!
Billy

**Comment by kashif** [comment]
all ok with me. I was planning on sending a PR but if you want to add it go ahead and if i have some additional fixes etc. I can then fix it on your side.

**Comment by lamberta** [comment]
Thank you!
Starting that PR here: https://github.com/tensorflow/models/pull/4768
Will get some more eyes on it on Monday.
